language: php
php:
- 7.1
cache:
  directories:
  - "$HOME/.composer"
before_script:
- cd src/
- composer install --no-dev
script:
- echo "No tests provided yet"
before_install:
- touch ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_899ee332488e_key -iv $encrypted_899ee332488e_iv
  -in digitalocean.enc -out ~\/.ssh/id_rsa -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa
- ssh $DEPLOY_USER@$DEPLOY_IP "cd /var/www/app-upload && git pull origin && ./update.sh"
