version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        extra_hosts:
            - "docker_host:192.168.0.104"
        volumes:
            - ./src:/var/www
        links:
            - database
            - cache
        ports:
            - "8001:80"
    database:
        image: mysql:5.5
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=schedlr"
            - "MYSQL_USERNAME=root"
        ports:
            - "33061:3306"
        volumes:
            - ./mysql:/var/lib/mysql
    cache:
        image: redis:4
        ports:
            - "63791:6379"
