version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        extra_hosts:
            - "docker_host:192.168.0.97"
        volumes:
            - ./src:/var/www
        links:
            - database
        ports:
            - "80:80"
    database:
        image: mysql:5.5
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=database"
            - "MYSQL_USERNAME=root"
        ports:
            - "33061:3306"
